### ISSUE TITLE
Development Status

### ISSUE THREAD

**Issue by Dave3o3** [spamihilator/spamihilator#1]
Hi!

First of all: GREAT TOOL! Thank you very much for your efforts!

Now my question: Is spamihilator still under development?

Thanks in advance!

**Comment by michel-kraemer** [comment]
From time to time I implement some minor features or bug fixes, but development has slowed down for the most part. What you see here is an attempt to re-implement Spamihilator in another programming language. It has nothing to do with the actual code.
